### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by aoyanl** [GuoleiSun/VSS-CFFM#1]

**Comment by aoyanl** [comment]
Hi,  I am interested in your work vss-cffm, and  have some questions about the setting of testing fps. You mentioned in your paper "conduct all experiments on 4 NVIDIA GPUs",  and i want to know which GPUs you are using. Is the fps in paper  measured with 4 gpus?

**Comment by GuoleiSun** [comment]
Hello, thanks for your interest. For all the experiments, our model is trained on 4 NVIDIA GPUs. For test, you can use any number of gpus. For computing fps, we use a single RTX 6000 GPU. Note that when computing fps, we assume that the features of reference frames (certain frames before the target frame) are already in the memory and available for use.

**Comment by aoyanl** [comment]
Thanks for your reply. And have you released the code of computing fps? If not, can you share this part of code？

**Comment by GuoleiSun** [comment]
Thanks for your interest. It is quite straightforward to compute the fps. Nevertheless, I will share this part later.
