### ISSUE TITLE
problem about Cityscapes dataset

### ISSUE THREAD

**Issue by ydhongHIT** [GuoleiSun/VSS-CFFM#12]
When I modify the config to perform video semantic segmentation, the error exists in https://github.com/GuoleiSun/VSS-CFFM/blob/8537cb54769fbdd5e67c75d4835bb3d90d0318e9/mmseg/datasets/custom.py#L1088
ValueError: invalid literal for int() with base 10: 'gtFine'. It seems that value_i_splits[-2] is 'gtFine' not a number.

**Comment by IxxdbxxI** [comment]
I want to know if you have solved this problem? Thanks!
