### ISSUE TITLE
Pytorch model definition code of the proposed model

### ISSUE THREAD

**Issue by RaymondWang987** [GuoleiSun/VSS-CFFM#5]
Thanks for releasing the code. Where can we find the pytorch model definition of VSS-CFFM? The VSS-CFFM is now presented by config file and MMSegmentation library. I cannot find pytorch model definition code of the proposed model.

**Comment by GuoleiSun** [comment]
Thanks for your interest. You can find the model definition is mmseg/models/decode_heads and mmseg/models/segmentors
