### ISSUE TITLE
request for the Pre-training weight used to train the cffm-model on VSPW

### ISSUE THREAD

**Issue by hjkhkhkjh12** [GuoleiSun/VSS-CFFM#6]
I am very lucky to be able to study and try your work. Your work is an eye-opener to me. I encountered some problems when reproducing your work. I used the segformer pre-training model weights provided by mmsegmentation and converted the model weights (specifically, running mit2mmseg.py in mmseg). I trained with this model weight and only got 16.08 miou on cffm-b0. Can you provide the weight of the pre-training model you use in your training?
Thank you!!!

**Comment by GuoleiSun** [comment]
Thanks for your interest

The pre-trained weights (on ImageNet) can be found in [here](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing), which are provided by [SegFormer](https://github.com/NVlabs/SegFormer)

**Comment by hjkhkhkjh12** [comment]
> Thanks for your interest
> 
> The pre-trained weights (on ImageNet) can be found in [here](https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing), which are provided by [SegFormer](https://github.com/NVlabs/SegFormer)

Thank you so much! I did it!
